<InfoCard>
    orientation: 'vertical'
    md_bg_color: app.theme_cls.primary_light
        
    AsyncImage:
        id: info_image
        source: root.icon
        on_load:
            self.fit_mode = 'fill'
      
    MDLabel:
        text: root.title
        theme_text_color: "Custom"
        text_color: app.theme_cls.primary_color
        font_style: 'Caption'
        adaptive_height: True
        shorten: True
        padding: '5dp'